import type { MetricClassification, SourceSystem } from "./source-of-truth";

export type CoreMetricId =
  | "gross_revenue"
  | "net_revenue"
  | "refunds"
  | "refund_rate"
  | "failed_payments"
  | "failed_payment_rate"
  | "purchases"
  | "leads"
  | "landing_page_views"
  | "cta_clicks"
  | "checkout_starts"
  | "checkout_conversion_rate"
  | "lead_to_purchase_rate"
  | "ad_spend"
  | "cpa"
  | "blended_roas"
  | "meta_reported_purchases"
  | "meta_purchase_value"
  | "estimated_stripe_fees"
  | "fixed_daily_expense_allocation"
  | "estimated_profit"
  | "daily_revenue_goal_progress"
  | "daily_purchase_goal_progress"
  | "utm_coverage"
  | "data_freshness"
  | "data_confidence";

export type MetricDefinition = {
  id: CoreMetricId;
  name: string;
  businessQuestion: string;
  sourceOfTruth: SourceSystem;
  secondaryComparisonSource?: SourceSystem;
  formula: string;
  classification: MetricClassification;
  requiredFields: string[];
  freshnessExpectation: string;
  missingDataBehavior: string;
  knownCaveats: string;
};

export const CORE_METRIC_IDS: CoreMetricId[] = [
  "gross_revenue",
  "net_revenue",
  "refunds",
  "refund_rate",
  "failed_payments",
  "failed_payment_rate",
  "purchases",
  "leads",
  "landing_page_views",
  "cta_clicks",
  "checkout_starts",
  "checkout_conversion_rate",
  "lead_to_purchase_rate",
  "ad_spend",
  "cpa",
  "blended_roas",
  "meta_reported_purchases",
  "meta_purchase_value",
  "estimated_stripe_fees",
  "fixed_daily_expense_allocation",
  "estimated_profit",
  "daily_revenue_goal_progress",
  "daily_purchase_goal_progress",
  "utm_coverage",
  "data_freshness",
  "data_confidence",
];

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  {
    id: "gross_revenue",
    name: "Gross revenue",
    businessQuestion: "How much money did Stripe collect before refunds?",
    sourceOfTruth: "stripe",
    formula: "Sum successful Stripe transaction amounts.",
    classification: "exact",
    requiredFields: ["transactions.amount_cents", "transactions.status"],
    freshnessExpectation: "Webhook real time, backfill/manual sync on demand.",
    missingDataBehavior: "Waiting for first Stripe sync.",
    knownCaveats: "Test-mode rows must not be shown as real business revenue.",
  },
  {
    id: "net_revenue",
    name: "Net revenue",
    businessQuestion: "How much revenue remains after refunds?",
    sourceOfTruth: "stripe",
    formula: "Gross revenue - refunds.",
    classification: "exact",
    requiredFields: ["transactions.amount_cents", "refunds.amount_cents"],
    freshnessExpectation: "Webhook real time, backfill/manual sync on demand.",
    missingDataBehavior: "Waiting for Stripe transactions and refunds.",
    knownCaveats: "Stripe fees are not subtracted from net revenue.",
  },
  {
    id: "refunds",
    name: "Refunds",
    businessQuestion: "How much money was returned to customers?",
    sourceOfTruth: "stripe",
    formula: "Sum Stripe refund amounts.",
    classification: "exact",
    requiredFields: ["refunds.amount_cents", "refunds.status"],
    freshnessExpectation: "Webhook real time, backfill/manual sync on demand.",
    missingDataBehavior: "Waiting for Stripe refund rows.",
    knownCaveats: "Partial refunds need to remain amount-based, not count-only.",
  },
  {
    id: "refund_rate",
    name: "Refund rate",
    businessQuestion: "What share of purchases are being refunded?",
    sourceOfTruth: "stripe",
    formula: "Refund count / purchase count.",
    classification: "exact",
    requiredFields: ["refunds.id", "transactions.id"],
    freshnessExpectation: "Webhook real time, backfill/manual sync on demand.",
    missingDataBehavior: "Unavailable until Stripe purchases exist.",
    knownCaveats: "Amount-based refund impact should be reviewed for partial refunds.",
  },
  {
    id: "failed_payments",
    name: "Failed payments",
    businessQuestion: "How many purchase attempts failed at payment?",
    sourceOfTruth: "stripe",
    formula: "Count failed Stripe payment rows.",
    classification: "exact",
    requiredFields: ["failed_payments.id", "failed_payments.created_at"],
    freshnessExpectation: "Webhook real time, backfill/manual sync on demand.",
    missingDataBehavior: "Waiting for Stripe failed payment rows.",
    knownCaveats: "Failed payment count is not the same as checkout starts.",
  },
  {
    id: "failed_payment_rate",
    name: "Failed payment rate",
    businessQuestion: "How much checkout demand is lost to declined payments?",
    sourceOfTruth: "stripe",
    secondaryComparisonSource: "ga4",
    formula: "Failed payments / verified checkout starts.",
    classification: "directional",
    requiredFields: ["failed_payments.id", "checkout_starts"],
    freshnessExpectation: "Stripe real time; checkout starts require GA4 or verified GHL tracking.",
    missingDataBehavior: "Unavailable until checkout starts are tracked.",
    knownCaveats: "Using Stripe payment attempts as checkout starts is only directional.",
  },
  {
    id: "purchases",
    name: "Purchases",
    businessQuestion: "How many customers bought Drum Mastery Suite?",
    sourceOfTruth: "stripe",
    secondaryComparisonSource: "meta_ads",
    formula: "Count successful Stripe purchases.",
    classification: "exact",
    requiredFields: ["transactions.status", "transactions.amount_cents"],
    freshnessExpectation: "Webhook real time, backfill/manual sync on demand.",
    missingDataBehavior: "Waiting for first Stripe transaction.",
    knownCaveats: "Meta purchases are attribution comparison only.",
  },
  {
    id: "leads",
    name: "Leads",
    businessQuestion: "How many prospects entered the funnel?",
    sourceOfTruth: "gohighlevel",
    formula: "Count GoHighLevel contacts/leads in the reporting window.",
    classification: "exact",
    requiredFields: ["ghl_contacts.id", "ghl_contacts.first_seen_at"],
    freshnessExpectation: "Manual GHL sync until scheduled sync exists.",
    missingDataBehavior: "Not connected until GoHighLevel sync has live rows.",
    knownCaveats: "Contact creation date may not equal form submission date.",
  },
  {
    id: "landing_page_views",
    name: "Landing page views",
    businessQuestion: "How many people reached the Drum Mastery Suite page?",
    sourceOfTruth: "ga4",
    formula: "Count GA4 landing_page_view events for the landing page URL, or page_view filtered to the landing page when landing_page_view is absent.",
    classification: "exact",
    requiredFields: ["event_name", "page_url", "event_timestamp"],
    freshnessExpectation: "Manual GA4 sync until scheduled sync exists.",
    missingDataBehavior: "Unavailable until GA4 credentials are configured and landing page view data exists.",
    knownCaveats: "GoHighLevel dashboard analytics should not be assumed to be API-accessible.",
  },
  {
    id: "cta_clicks",
    name: "CTA clicks",
    businessQuestion: "How many visitors clicked the main purchase CTA?",
    sourceOfTruth: "ga4",
    formula: "Count GA4 primary_cta_click events.",
    classification: "exact",
    requiredFields: ["event_name", "page_url", "utm fields"],
    freshnessExpectation: "Manual GA4 sync until scheduled sync exists.",
    missingDataBehavior: "Unavailable until GA4 event tracking is configured.",
    knownCaveats: "Requires GTM/GA4 event instrumentation.",
  },
  {
    id: "checkout_starts",
    name: "Checkout starts",
    businessQuestion: "How many people started checkout?",
    sourceOfTruth: "ga4",
    secondaryComparisonSource: "gohighlevel",
    formula: "Count verified checkout_start events.",
    classification: "exact",
    requiredFields: ["checkout_start event", "event_timestamp"],
    freshnessExpectation: "Manual GA4 sync until scheduled sync exists.",
    missingDataBehavior: "Unavailable until GA4 checkout_start tracking is configured.",
    knownCaveats: "GA4 checkout_start is required; never infer checkout starts from Stripe purchases or GoHighLevel contacts.",
  },
  {
    id: "checkout_conversion_rate",
    name: "Checkout conversion rate",
    businessQuestion: "What share of checkout starts become purchases?",
    sourceOfTruth: "ga4",
    secondaryComparisonSource: "stripe",
    formula: "Stripe purchases / verified checkout starts.",
    classification: "exact",
    requiredFields: ["checkout_starts", "transactions.id"],
    freshnessExpectation: "GA4 and Stripe fresh within reporting window.",
    missingDataBehavior: "Unavailable until checkout starts are tracked.",
    knownCaveats: "Stripe purchases are truth; GA4 purchase events are comparison only.",
  },
  {
    id: "lead_to_purchase_rate",
    name: "Lead-to-purchase rate",
    businessQuestion: "How well do leads turn into buyers?",
    sourceOfTruth: "gohighlevel",
    secondaryComparisonSource: "stripe",
    formula: "Stripe purchases / GoHighLevel leads.",
    classification: "exact",
    requiredFields: ["ghl_contacts.id", "transactions.id"],
    freshnessExpectation: "GHL manual sync plus Stripe live data.",
    missingDataBehavior: "Unavailable until GoHighLevel has live lead rows.",
    knownCaveats: "Lead and purchase identity matching is not yet hardened.",
  },
  {
    id: "ad_spend",
    name: "Ad spend",
    businessQuestion: "How much did Meta spend?",
    sourceOfTruth: "meta_ads",
    formula: "Sum Meta insights spend.",
    classification: "exact",
    requiredFields: ["ad_daily_metrics.spend_cents"],
    freshnessExpectation: "Manual Meta sync until scheduled sync exists.",
    missingDataBehavior: "Waiting for first Meta sync.",
    knownCaveats: "Meta tokens can expire if using temporary Graph API Explorer tokens.",
  },
  {
    id: "cpa",
    name: "CPA",
    businessQuestion: "How much ad spend is required per Stripe purchase?",
    sourceOfTruth: "meta_ads",
    secondaryComparisonSource: "stripe",
    formula: "Meta ad spend / Stripe purchases.",
    classification: "directional",
    requiredFields: ["ad_daily_metrics.spend_cents", "transactions.id"],
    freshnessExpectation: "Meta and Stripe fresh for the same reporting window.",
    missingDataBehavior: "Unavailable until both Meta spend and Stripe purchases exist.",
    knownCaveats: "Label as blended CPA unless attribution is clean.",
  },
  {
    id: "blended_roas",
    name: "Blended ROAS",
    businessQuestion: "How much Stripe net revenue came back per dollar of Meta spend?",
    sourceOfTruth: "stripe",
    secondaryComparisonSource: "meta_ads",
    formula: "Stripe net revenue / Meta ad spend.",
    classification: "directional",
    requiredFields: ["transactions.amount_cents", "refunds.amount_cents", "ad_daily_metrics.spend_cents"],
    freshnessExpectation: "Meta and Stripe fresh for the same reporting window.",
    missingDataBehavior: "Unavailable until Meta spend exists.",
    knownCaveats: "This is blended business ROAS, not ad-level ROAS.",
  },
  {
    id: "meta_reported_purchases",
    name: "Meta-reported purchases",
    businessQuestion: "How many purchases does Meta attribute to ads?",
    sourceOfTruth: "meta_ads",
    secondaryComparisonSource: "stripe",
    formula: "Sum purchase actions from Meta insights.",
    classification: "directional",
    requiredFields: ["ad_daily_metrics.actions"],
    freshnessExpectation: "Manual Meta sync until scheduled sync exists.",
    missingDataBehavior: "Waiting for first Meta sync.",
    knownCaveats: "Use for attribution mismatch detection only.",
  },
  {
    id: "meta_purchase_value",
    name: "Meta purchase value",
    businessQuestion: "Does Meta have revenue/action value data?",
    sourceOfTruth: "meta_ads",
    secondaryComparisonSource: "stripe",
    formula: "Sum purchase action_values from Meta insights.",
    classification: "directional",
    requiredFields: ["ad_daily_metrics.action_values"],
    freshnessExpectation: "Manual Meta sync until scheduled sync exists.",
    missingDataBehavior: "Unavailable because Meta purchase value may be missing.",
    knownCaveats: "Stripe remains the money source of truth.",
  },
  {
    id: "estimated_stripe_fees",
    name: "Estimated Stripe fees",
    businessQuestion: "Roughly how much processing cost should be reserved?",
    sourceOfTruth: "stripe",
    formula: "2.9% of Stripe gross revenue + $0.30 per successful transaction.",
    classification: "estimated",
    requiredFields: ["transactions.amount_cents", "transactions.id"],
    freshnessExpectation: "Calculated whenever Stripe purchases are available.",
    missingDataBehavior: "Unavailable until Stripe purchases exist.",
    knownCaveats: "Estimated until Stripe balance transaction fees are synced.",
  },
  {
    id: "fixed_daily_expense_allocation",
    name: "Fixed daily expense allocation",
    businessQuestion: "How much known monthly software cost should today carry?",
    sourceOfTruth: "manual_settings",
    formula: "$117 / 30 days.",
    classification: "estimated",
    requiredFields: ["business settings fixed expenses"],
    freshnessExpectation: "Manual settings update whenever expenses change.",
    missingDataBehavior: "Unavailable only if manual settings are missing.",
    knownCaveats: "Known software only; not full business accounting.",
  },
  {
    id: "estimated_profit",
    name: "Estimated profit",
    businessQuestion: "Was the business likely profitable in the reporting window?",
    sourceOfTruth: "stripe",
    secondaryComparisonSource: "meta_ads",
    formula: "Stripe net revenue - Meta spend - estimated Stripe fees - fixed expense allocation.",
    classification: "estimated",
    requiredFields: ["net_revenue", "ad_spend", "estimated_stripe_fees", "fixed_daily_expense_allocation"],
    freshnessExpectation: "Calculated when Stripe and Meta data are fresh.",
    missingDataBehavior: "Unavailable until Stripe and Meta data exist.",
    knownCaveats: "Does not include unknown contractors, taxes, chargeback fees, or non-listed expenses.",
  },
  {
    id: "daily_revenue_goal_progress",
    name: "Daily revenue goal progress",
    businessQuestion: "Is today on pace for the $30,000 monthly goal?",
    sourceOfTruth: "manual_settings",
    secondaryComparisonSource: "stripe",
    formula: "Stripe net revenue / $1,000 daily pace target.",
    classification: "estimated",
    requiredFields: ["transactions.amount_cents", "monthlyRevenueGoalCents"],
    freshnessExpectation: "Last 24 hours in America/Chicago.",
    missingDataBehavior: "Waiting for Stripe rows in the reporting window.",
    knownCaveats: "Uses a flat 30-day month pace target.",
  },
  {
    id: "daily_purchase_goal_progress",
    name: "Daily purchase goal progress",
    businessQuestion: "Is today on pace for about 15 purchases?",
    sourceOfTruth: "manual_settings",
    secondaryComparisonSource: "stripe",
    formula: "Stripe purchases / 15 daily purchase target.",
    classification: "estimated",
    requiredFields: ["transactions.id", "productPriceCents"],
    freshnessExpectation: "Last 24 hours in America/Chicago.",
    missingDataBehavior: "Waiting for Stripe purchases in the reporting window.",
    knownCaveats: "Purchase target rounds up from the $30,000 monthly revenue goal at $67/product.",
  },
  {
    id: "utm_coverage",
    name: "UTM coverage",
    businessQuestion: "How much purchase data can be attributed back to campaigns?",
    sourceOfTruth: "stripe",
    secondaryComparisonSource: "gohighlevel",
    formula: "Purchases with utm_source, utm_campaign, and utm_content / total purchases.",
    classification: "exact",
    requiredFields: ["utm_source", "utm_campaign", "utm_content"],
    freshnessExpectation: "Calculated whenever Stripe purchases are available.",
    missingDataBehavior: "Unavailable until Stripe purchases exist.",
    knownCaveats: "If 0%, check whether GoHighLevel passes UTMs into Stripe metadata.",
  },
  {
    id: "data_freshness",
    name: "Data freshness",
    businessQuestion: "Can the user trust that the dashboard is current?",
    sourceOfTruth: "manual_settings",
    formula: "Evaluate latest sync_runs/source status by source.",
    classification: "directional",
    requiredFields: ["sync_runs.source", "sync_runs.finished_at", "sync_runs.status"],
    freshnessExpectation: "Source-specific; live webhooks should be current, manual syncs may be stale.",
    missingDataBehavior: "Waiting for first sync.",
    knownCaveats: "No scheduled syncs yet.",
  },
  {
    id: "data_confidence",
    name: "Data confidence",
    businessQuestion: "How much should the user trust a metric or recommendation?",
    sourceOfTruth: "manual_settings",
    formula: "Required sources connected + fresh + required fields present.",
    classification: "directional",
    requiredFields: ["source status", "freshness", "required metric fields"],
    freshnessExpectation: "Calculated with each dashboard read.",
    missingDataBehavior: "Unavailable when required source is not connected.",
    knownCaveats: "Confidence is a guardrail, not a replacement for source audit.",
  },
];

export function getMetricDefinition(id: CoreMetricId) {
  return METRIC_DEFINITIONS.find((metric) => metric.id === id) ?? null;
}
